### ISSUE TITLE
Support uv run

### ISSUE THREAD

**Issue by bluss** [bluss/pyproject-local-kernel#13]
The following configuration almost works right now:

```toml
[tool.pyproject-local-kernel]
python-cmd = ["uv", "run", "--with", "ipykernel", "python"]
```

(installing ipykernel if missing is a great feature.)

The following problems remain

- With no configuration change, interrupting computation does not work correctly
  - https://github.com/astral-sh/uv/issues/3095 or other solution(?) required to make interrupt_mode="signal" work
- papermill execution does not work (Linux), also because of interrupt_mode
- Kernel setting interrupt_mode="message" seems to be a working workaround on Linux, but Github issues says it will not work with ipykernel on Windows (and an experiment confirmed this, #14)
